name: Build OSRM Greece Map
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Greece Map from Geofabrik
        run: |
          wget http://geofabrik.de -O greece.osm.pbf

      - name: Process Map with Stable OSRM v5.24.0
        run: |
          docker run -v ${{ github.workspace }}:/data osrm/osrm-backend:v5.24.0 osrm-extract -p /usr/local/share/osrm/profiles/car.lua /data/greece.osm.pbf
          docker run -v ${{ github.workspace }}:/data osrm/osrm-backend:v5.24.0 osrm-contract /data/greece.osrm

      - name: Pack and Upload Ready OSRM File
        uses: actions/upload-artifact@v4
        with:
          name: greece-offline-osrm
          path: ${{ github.workspace }}/greece.osrm

